config/routes.rb
Opencurriculum::Application.routes.draw do
  root :to => 'high_voltage/pages#show', :id => 'home'
  resources :curricula

end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
  set_table_name 'curricula' # FIXME: Why is this necessary?
  acts_as_nested_set
  attr_protected :lft, :rgt, :depth
end
CurriculumDecorator # hack to make #decorate method work in dev with cache_classes

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/curricula_controller.rb
class CurriculaController < InheritedResources::Base
  def index
    @curricula = end_of_association_chain.where(parent_id: nil).decorate
  end

  def new
    build_resource
    @curriculum.parent_id = params[:parent_id]
  end

  protected
  def collection
    @curricula ||= end_of_association_chain.decorate
  end

  def resource
    @curriculum ||= super.decorate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/curricula/_form.html.haml
.curriculum-form
  = semantic_form_for @curriculum do |f|
    = f.semantic_errors
    = f.inputs do
      = f.input :name
      = f.input :content
      = f.hidden_field :parent_id
    = f.buttons do
      = f.commit_button button_html: { class: 'btn primary' }

app/views/curricula/_tree.html.haml
%li{ id: dom_id(curriculum) }
  = link_to curriculum.name, curriculum
  - unless curriculum.leaf?
    = content_tag :ul do
      - curriculum.children.each do |child|
        = render partial: "tree", locals: { curriculum: child.decorate }

app/views/curricula/edit.html.haml
%h2 Edit Curriculum
= render partial: 'form'

app/views/curricula/index.html.haml
.curricula-module
  %ul
    - @curricula.each do |curriculum|
      %li= link_to curriculum.title, curriculum

app/views/curricula/new.html.haml
%h2 New Curriculum
= render partial: 'form'

app/views/curricula/show.html.haml
.curriculum-module
  %h2= @curriculum.title
  %ul.pills
    %li= link_to 'New Sub-Curriculum', new_curriculum_path(parent_id: @curriculum.id)
    %li= link_to 'Edit', edit_curriculum_path(@curriculum), rel: 'edit-curriculum'
  = @curriculum.content

  - unless @curriculum.leaf?
    = content_tag :ul do
      - @curriculum.children.each do |child|
        = render partial: "tree", locals: { curriculum: child.decorate }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OpenCurriculum
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application'
  = csrf_meta_tags 

  %body
    %div.topbar
      %div.topbar-inner
        %div.container-fluid
          = link_to 'OpenCurriculum', root_path, class: 'brand'
          %ul.nav
            %li= link_to 'Curricula', curricula_path
    %div.container-fluid
    #content_wrap
      = yield
    %footer

app/views/pages/home.html.haml
.hero-unit
  %h1 OpenCurriculum
  %p
    OpenCurriculum is a tool to build different curriculums.
  %p
    %a.btn.primary.large Learn More

%h4 Check it out
= link_to 'Start a new curriculum', new_curriculum_path, :class => 'btn primary'

%h4 Features
%ul.features
  %li Thing
  %li Better Thing
  %li CRAAAAAAZY Thing
  %li Sexy.
  %li Won't murder anyone.